# Generated by Django 2.1.4 on 2018-12-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181217_1031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='SubjectList',
        ),
    ]
